name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: "9089"
            runner: macos-15 # aarch64-darwin
          - host: "9099"
            runner: macos-13 # x86_64-darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: nix flake check
        run: nix flake check

      - name: build darwinConfigurations.${{ matrix.host }}
        run: nix build ".#darwinConfigurations.${{ matrix.host }}.system" -L
